# SPDX-License-Identifier: GPL-2.0

# KDIR ?= ../linux
KDIR ?= /home/alan/Project/Rust/OS-4/cicv-r4l-3-lliYanze/linux/

default:
	$(MAKE) -C $(KDIR) M=$$PWD


# obj-$(CONFIG_RUST_E1000)		+= r4l_e1000_demo.o
